unique_name: ProductDim
object_type: dimension
label: ProductDim
hierarchies:
  - unique_name: dimproduct_dimension Hierarchy
    label: dimproduct_dimension Hierarchy
    levels:
      - unique_name: productline
      - unique_name: dimproduct_dimension Level
level_attributes:
  - unique_name: dimproduct_dimension Level
    label: dimproduct_dimension Level
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: false
    key_columns:
      - productkey
    name_column: englishproductname
  - unique_name: productline
    label: productline
    contains_unique_names: false
    dataset: dimproduct
    key_columns:
      - productline
    name_column: productline
type: standard
