unique_name: ProductDim
object_type: dimension
label: ProductDim
calculation_groups:
  - unique_name: ProductDim Calculation Group
    label: ProductDim Calculation Group
    calculated_members:
      - unique_name: Current
        template: Current
        use_input_metric_format: true
      - unique_name: test
        expression: >-
          ([ProductDim].[dimproduct_dimension Hierarchy].[productline].&[M],
          [Measures].currentMember)
        use_input_metric_format: true
hierarchies:
  - unique_name: dimproduct_dimension Hierarchy
    label: dimproduct_dimension Hierarchy
    levels:
      - unique_name: productline
      - unique_name: dimproduct_dimension Level
level_attributes:
  - unique_name: dimproduct_dimension Level
    label: dimproduct_dimension Level
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: false
    key_columns:
      - productkey
    name_column: englishproductname
  - unique_name: productline
    label: productline
    contains_unique_names: false
    dataset: dimproduct
    key_columns:
      - productlinetrimed
    name_column: productlinetrimed
type: standard
